### PR TITLE
UI Restart Button

### LINKED ISSUE #1098: windows ui "reboot-visor" handling
**Describe the bug**
When using skywire app on windows the following error comes up when trying to reboot the visor.

**Environment information:**

- OS: Windows, v0.6.0-rc2

**Steps to Reproduce**

1. Go to Menu 
2. Click on "reboot visor"

**Actual behavior**
image

**Expected behavior**
either restart the application or return a message like : "This function doesn't work on windows"

**Additional context**

**Possible implementation**
Hints to fix the bug.

### PR DESCRIPTION
**Pull request by mrpalide**
Did you run `make format && make check`? Yes

Fixes #1098

 Changes:	
- add windows logic for restart button

How to test this PR:
- `make build-windows` or `make build-systray-windows`
- run hypervisor
- test restart button

Note: Also be good if test by windows installer.

### CODE REVIEW

**Comment by ersonp** [comment]
For `make build-windows` and  `make build-systray-windows` 
- Starting hypervisor on `powershell` and `cmd` without admin
  - rebooting the visor give a `user account control` popup in windows and it is restarted without any issue. The new cmd starts as admin with the following logs.
  	```
	[2022-04-22T10:55:53+05:30] INFO [visor]: Starting new instance of executable (cmd: "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe Start-Process D:\\Code\\go\\skywire\\skywire-visor.exe \"-c .\\skywire-config.json\" -Verb RunAs")
	[2022-04-22T10:55:54+05:30] INFO [visor]: New instance started successfully, exiting from the old one
	2022/04/22 10:55:54 [DESKTOP-J9DSNEK/rBppEKpZlU-000004] "POST http://localhost:8000/api/visors/03ef0f0033e3603911d2448a4d96b72399df0c2b93d3d2abe13e696d269ff641fd/restart HTTP/1.1" from [::1]:51427 - 200 5B in 1.0415355s
	[2022-04-22T10:55:54+05:30] INFO [visor]: Exiting
	```
  - rebooting the visor again from this point is hit or miss, sometimes the new cmd starts as admin and everything works or it doesn't start as admin and the hypervisor module is not initialized.
- Starting hypervisor on `powershell` and `cmd` with admin
  - rebooting the visor gives no pop-up and the new cmd window is hit or miss to start as admin and works the same as mentioned above.
  - the previous cmd/powershell window gives an error
	```
	2022/04/22 10:56:49 [DESKTOP-J9DSNEK/5sdY6bPjn7-000001] "GET http://localhost:8000/api/visors/03ef0f0033e3603911d2448a4d96b72399df0c2b93d3d2abe13e696d269ff641fd/summary HTTP/1.1" from 127.0.0.1:51460 - 200 1225B in 20.5481772s
	[2022-04-22T10:56:54+05:30] INFO [visor]: Starting new instance of executable (cmd: "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe Start-Process D:\\Code\\go\\skywire\\skywire-visor.exe \"-c .\\skywire-config.json\" -Verb RunAs")
	[2022-04-22T10:56:54+05:30] ERROR [visor]: Failed to start new instance: <nil>
	2022/04/22 10:56:54 [DESKTOP-J9DSNEK/5sdY6bPjn7-000002] "POST http://localhost:8000/api/visors/03ef0f0033e3603911d2448a4d96b72399df0c2b93d3d2abe13e696d269ff641fd/restart HTTP/1.1" from 127.0.0.1:51460 - 200 5B in 192.546ms
	[2022-04-22T10:56:54+05:30] INFO [visor]: Exiting
	```

The reboot seems to be flaky when the cmd/powershell is already started as admin.

In linux for both sudo and non sudo and systray and non systray
- second reboot doesn't work
  ```
  [2022-04-22T11:32:02+05:30] INFO [visor_rpc:CLI]: Request processed. _elapsed="11.482µs" _method="GetAppConnectionsSummary" _received="11:32AM" error="no such app" input=0xc000647b80 output=&[]
  [2022-04-22T11:32:03+05:30] INFO [visor]: Starting new instance of executable (cmd: "/bin/sh -c sleep 2; ./skywire-visor -c skywire-config.json")
  [2022-04-22T11:32:03+05:30] ERROR [visor]: Failed to start new instance: fork/exec /bin/sh: operation not permitted
  ```
- restarting after the above error gives this 
  ```
  [2022-04-22T11:34:02+05:30] INFO [visor]: Starting new instance of executable (cmd: "/bin/sh /bin/sh -c sleep 2; ./skywire-visor -c skywire-config.json") 
  /bin/sh: 1: Syntax error: ")" unexpected
  [2022-04-22T11:34:02+05:30] ERROR [visor]: Failed to start new instance: exit status 2
  ```
- closing the visor with `Ctrl+C` after this gets stuck and another `Ctrl+C` is needed (this also happens after second reboot attempt)
  image
  image

**Comment by mrpalide** [comment]
Update on PR:
After investigation on problem with restart button on build from source on Linux, I found that after first restart, the ppid of current pid not detected correct and return whole of system as parent, then `operation not permitted` occurs.
So we decided to chose second solution for restart button.
If `BuiltTag` in summary of  visor be `Windows` (for Windows msi installer) or `Package` (for deb, aur, mac and ... packages) then restart button appear and work on UI, otherwise no need to be there at all.
`Windows` built tag now available on window installer msi, but I think @0pcom need add it to packages, and also we need your help @Senyoret1 to handle it in UI side.

**Review by ersonp — APPROVED** [review]
Working on linux packages

**Comment by mrpalide** [comment]
We just handle button on UI. No need in back at all.

**Pull request closed without merging**
