### PR TITLE
Add language portuguese

### PR DESCRIPTION
**Pull request by xpecex**

### CODE REVIEW

**Comment by jdknives** [comment]
@xpecex thanks for the PR and translation. Please sign the CLA.

**Comment by xpecex** [comment]
Done!

**Comment by jdknives** [comment]
@xpecex thanks 

@Senyoret1 please review this briefly for functionality.

**Comment by Senyoret1** [comment]
The automatic tests pass and after taking a look at the file it appears that there are no errors.

However, the PR can not be merged into develop, because there are multiple conflicts. Maybe this also means that several new texts will not be translated.

**Comment by xpecex** [comment]
how can we fix this?

**Comment by jdknives** [comment]
@xpecex I see the issue. You pointed your PR at `master` branch but we need to merge these changes into `develop`. Can you rebase your PR please? I changed the target branch to `develop`.

**Review by jdknives — APPROVED** [review]

**Pull request merged**
