### PR TITLE
Add method to get visor's config value via RPC call

### LINKED ISSUE #345: Give app an ability to request config changes from the visor
**Feature description**

Apps should be able to request config changes from the visor. This may done as discussed on Discord:

```
i think the best solution is if we add a function in appserver.RPCGateway along the lines of func (g *RPCGateway) Value(name string, v interface{}) error
```
but also, thinking further, it might not work well with the nested values. probably should be thought of deeper

### PR DESCRIPTION
**Pull request by Darkren**
Did you run `make format && make check`?
Yes

Fixes #345 

 Changes:	
- Switch to develop branch of Dmsg
- Add method to get visor's config value via RPC call

### CODE REVIEW

**Review by nkryuchkov — APPROVED** [review]

**Comment by evanlinjin** [comment]
Because apps are meant to use this, shouldn't this be implemented here: https://github.com/SkycoinProject/skywire-mainnet/blob/master/pkg/app/appserver/rpc_gateway.go ?

**Comment by evanlinjin** [comment]
Or are you thinking to expose the entirety of `visor.RPC` to apps?

**Comment by Darkren** [comment]
@evanlinjin I was thinking to create the RPC client instance within the app, yes. cause appserver rn is only responsible for networking. and it doesn't even have access to the visor instance, so I was willing to keep it this way. but this is truly discussable

**Comment by evanlinjin** [comment]
@Darkren Is this feature urgent right now? Do you mind if I am made responsible for continuing with this to find an elegant solution?

**Comment by Darkren** [comment]
@evanlinjin I don't, just please let me know, when you're done. I'll need to integrate this within VPN apps

**Pull request closed without merging**
