### PR TITLE
Update the UI theme

### LINKED ISSUE #260: Change colour background of manager
**Feature description**

Let us go with this option: 

grafik

### PR DESCRIPTION
**Pull request by Senyoret1**
Did you run `make format && make check`?
The go code was not changed. `npm run lint` and `npm run build` were used.

Fixes #260 

 Changes:	
- This PR changes the theme of the Skywire manager, to make it look like the one in the issue.

How to test this PR:
Check the changes in the Skywire manager.

NOTE: at this point most of the pages have the dark theme, except for the options page. The modal windows have not been changed, so the design still needs improvements.

### CODE REVIEW

**Comment by Senyoret1** [comment]
The last commit includes the following changes:
- Now the options page of the manager uses the dark theme.
- Generic styles for making the fields and buttons work well with the dark theme were added.

**Comment by Senyoret1** [comment]
The last commit includes the following changes:
- The design of the modal windows was changed to work better with the dark theme.
- Visual improvements were added to several modal windows, appart from the ones applied to the generic modal window component.
- The design of the modal window for updating one or all visors at the same time has a lot of changes and some potential problems in edge cases were fixed.
- A bug with the theme background was solved.
- A bug with the login page was fixed.
- Some other small fixes.

**Comment by Senyoret1** [comment]
The last commits include the following changes:
- `SelectOptionComponent` was improved and now if replaces several other modal windows, to simplify the code and ensure a more consistent design.
- An inconsistency with the selection of the default transport, in the transport creation modal window, was solved.
- A problem with modal windows without scroll bars was solved.
- A problem with the layout just after initiating navigation from the visor details page was solved.
- Some other small improvements.

**Comment by Senyoret1** [comment]
The last commits include the following changes:
- The problem with the Travis test was fixed.
- The way in which the scss imports are made was changed, to avoid repeated styles.

**Comment by jdknives** [comment]
@Senyoret1 I sent some requests/ideas on TG.

**Comment by Senyoret1** [comment]
The last commit includes the following changes:
- Now the background is darker.
- Now the flag button has a white background.
- Now the menu does not have a clear gradient at the borders.

**Review by jdknives — APPROVED** [review]

**Pull request merged**
