### PR TITLE
Fix refreshing of state of the app.

### LINKED ISSUE #571: VPN-Client process finishes in background but UI shows status "green" aka running
**Describe the bug**
The vpn-client stops because of any problem I can't see at the moment but the UI shows it is running.

**Environment information:**

- OS: e.g. Linux
- Platform: Linux 5.4.0-42-generic x86_64

**Steps to Reproduce**

1. Wait for the vpn-client to stop in background
2. Try to stop it via the button in the UI

**Actual behavior**
An OS: error pops up, that the process has already finished

**Expected behavior**
The status of the app should get updated and shown as stop if the process stops in background

**Additional Feature Request:**

How about a column in the Application overview of the UI where the status of the app or 
other useful information is printed:
(e.g. for vpn-client: "TUN tun0", "closed network" ...)
(eg. for skychat: open chats: x, unread messages: y)

### PR DESCRIPTION
**Pull request by taras-skycoin**
Did you run `make format && make check`?

Fixes #571

 Changes:	
-	Add an extended check for the status of the app. 

How to test this PR:
1. Start VPN-client
2. Check the state of the app on the page of the visor
3. Kill the process of the app 
4. Check if the status on-page of the app changed after some delay.

### CODE REVIEW

**Review by jdknives — APPROVED** [review]
Works smoothly. Well done.

**Review by Darkren — APPROVED** [review]
Great job!

**Comment by i-hate-nicknames** [comment]
Is this a vpn specific issue? Works locally for skychat

**Comment by jdknives** [comment]
@i-hate-nicknames we only saw this issue with VPN so far.

**Pull request merged**
