### PR TITLE
Fix/web ui terminal hypervisor

### LINKED ISSUE #605: Panic when accessing Terminal UI
**Describe the bug**
When accessing the terminal UI on `develop` on the hypervisor machine, the UI does not return anything and the hypervisor logs a panic. 

```
 panic: runtime error: invalid memory address or nil pointer dereference
 
 -> github.com/skycoin/skywire/pkg/visor.(*Hypervisor).getPty.func1
 ->   /Users/work/go/src/github.com/skycoin/skywire/pkg/visor/hypervisor_unix.go:30

    github.com/skycoin/skywire/pkg/visor.(*Hypervisor).withCtx.func1
      /Users/work/go/src/github.com/skycoin/skywire/pkg/visor/hypervisor.go:1092
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi.(*Mux).routeHTTP
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/mux.go:431
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/skycoin/skywire/pkg/visor/usermanager.(*UserManager).Authorize.func1
      /Users/work/go/src/github.com/skycoin/skywire/pkg/visor/usermanager/user_manager.go:156
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi.(*Mux).ServeHTTP
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/mux.go:70
    github.com/go-chi/chi.(*Mux).Mount.func1
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/mux.go:298
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi.(*Mux).routeHTTP
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/mux.go:431
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi.(*Mux).ServeHTTP
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/mux.go:70
    github.com/go-chi/chi.(*Mux).Mount.func1
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/mux.go:298
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi.(*Mux).routeHTTP
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/mux.go:431
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/skycoin/dmsg/httputil.SetLoggerMiddleware.func1.1
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/skycoin/dmsg/httputil/httputil.go:94
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi/middleware.Recoverer.func1
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/middleware/recoverer.go:37
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi/middleware.RequestLogger.func1.1
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/middleware/logger.go:46
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi/middleware.RealIP.func1
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/middleware/realip.go:34
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi/middleware.RequestID.func1
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/middleware/request_id.go:76
    net/http.HandlerFunc.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2012
    github.com/go-chi/chi.(*Mux).ServeHTTP
      /Users/work/go/src/github.com/skycoin/skywire/vendor/github.com/go-chi/chi/mux.go:86
    net/http.serverHandler.ServeHTTP
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2807
    net/http.(*conn).serve
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:1895
    created by net/http.(*Server).Serve
      /usr/local/Cellar/go/1.14.4/libexec/src/net/http/server.go:2933
    
2020/11/16 15:40:03 [works-MacBook-Pro.local/42iJkYGvp9-000072] "GET http://localhost:8000/pty/032bda69d2ea01bef1dfb1054f8119f5085977452ea84412a072fa8b65bbe043fd HTTP/1.1" from [::1]:62030 - 500 0B in 779.051µs
```

**Environment information:**

- OS: e.g. MacOS
- reproduced in Safari and Firefox

**Steps to Reproduce**
1. Setup hypervisor on develop. 
2. Go to UI of hypervisor and try to start up terminal from top right corner menu. Select full-terminal.

**Additional context**
When dialing the UI for non-hypervisor visors, everything works as expected.

### PR DESCRIPTION
**Pull request by i-hate-nicknames**
Did you run `make format && make check`?
yes

Fixes #605 

 Changes:

How to test this PR:
Go to hypervisor web api, select hypervisor in the list of visors, click actions button at the top right and select Terminal/Full Terminal

The issue with terminal in hypervisor had most likely appeared after merging visor and hypervisors under the same entity. Previously, hypervisor would connect to visors using dmesg. There is a package for that, called dmesgpty that offers exposing pty (pseudo terminal) over dmsg transport. 

I played around for a while trying to create a pty locally and just serve it over websockets to the client, but it proved to be more architecturally difficult than I originally anticipated. 

In this implementation I simply allowed a visor to connect to itself and created a dmsg pty at hypervisor start. This way it minimizes changes to the code (and therefore the risk introducing bugs), as well as no increase in the overall complexity.

On the other hand, we make from a node to itself over dmsg, which obviously is redundant. What are the shortcomings of this approach? Terminal interaction seems to me lightweight (infrequent request-response of small amount text). Could there be use-cases in which this would cause performance issues?

Additionally, I bumped creack/pty to 1.1.11, as the older version had a [bug](https://github.com/creack/pty/issues/96) that didn't allow using the terminal.

### CODE REVIEW

**Review by jdknives — APPROVED** [review]
Works. Code looks fine to me. But please fix linter. Good job!

**Comment by jdknives** [comment]
@i-hate-nicknames regarding potential downsides of using `pty` over `dmsg`:

- we do not use the `pty` too frequently and do not send an excessive amount of data over it

therefore the only downside which I can see is the inability of the visor to manage itself over dmsgpty when `dmsg` is unavailable. But in this case the user might as well use the local terminal. Because of this possibility, I actually think it is rather rare that a user would use the hypervisor UI for the hypervisor itself. But I would like to keep this option just to be consistent.

**Review by Darkren — APPROVED** [review]
Great job!

**Comment by Darkren** [comment]
@i-hate-nicknames @jdknives the only problem is that build keeps failing

**Pull request merged**
