### PR TITLE
fix various issues

### LINKED ISSUE #1779: `skywire cli proxy start` not working as expected v1.3.20
```
[2024-03-20T10:44:06.503768555-05:00] DEBUG (STDOUT) [proc:skysocks-client:478496d5502c46c59fba81ee1670026a]: unknown flag: --srv

```

but the flag IS THERE

```
$ skywire app skysocks-client --help

  ┌─┐┬┌─┬ ┬┌─┐┌─┐┌─┐┬┌─┌─┐   ┌─┐┬  ┬┌─┐┌┐┌┌┬┐
  └─┐├┴┐└┬┘└─┐│ ││  ├┴┐└─┐───│  │  │├┤ │││ │
  └─┘┴ ┴ ┴ └─┘└─┘└─┘┴ ┴└─┘   └─┘┴─┘┴└─┘┘└┘ ┴



Flags:
      --addr string   Client address to listen on (default ":1080")
      --http string   http proxy mode
      --srv string    PubKey of the server to connect to
  -v, --version       version for skysocks-client

```

If I change the autostart in the config to true

```
			{
				"name": "skysocks-client",
				"binary": "skywire",
				"args": [
					"app",
					"skysocks-client",
					"--addr",
					":1080",
					"--srv",
					"031952d79eca8852a7c9fc2ae24ff16ddfe00665f62494845382fa53a8dab4ac4b"
				],
				"auto_start": true,
				"port": 13
			},

```

and restart the visor ; THEN IT WORKS. Why???

### PR DESCRIPTION
**Pull request by mrpalide**
Did you run `make format && make check`? Yes

Fixes #1779 #1769 #1753 #1694

 Changes:	
- Fix issues on Windows and Mac installer based on v1.3.20-rc1
- Fix start and stop issue on proxy/vpn (include ctrl+c command)
- Fix `--timeout` flag on start proxy/vpn
- Fix `--http` flag to skysocks to serve httpproxy beside socks5

How to test this PR:
You can run visor and trying to start/stop proxy and vpn by these commands:
- `skywire cli proxy start --timeout 30 --http :1010`
- `skywire cli vpn start --timeout 20`
- check `ctrl+c` command during running apps
- For fixing installers, I'll push `v1.3.20-rc2` after merging this PR.

### CODE REVIEW

**Comment by 0pcom** [comment]
Note there are windows machines of arm64 architecture

**Comment by 0pcom** [comment]
```
$ skywire cli proxy start -k 03419b3c3f9db0404b44afc532a91eb2c108499f7575d0e7937dd8d076d385b607
Starting..............................
Stopped!
```
seems says it stopped, about the time it was actually started

```
[2024-03-21T08:28:01.505341862-05:00] DEBUG (STDOUT) [proc:skysocks-client:82e01b3b49514a46857f542a157ad816]: Serving proxy client :1080
[2024-03-21T08:28:01.51240123-05:00] DEBUG (STDOUT) [proc:skysocks-client:82e01b3b49514a46857f542a157ad816]: Serving http proxy :1081
```

We shouldn't auto-start the http proxy. Especially in instances where I need to test a lot of proxy servers, the http proxy running just takes up another port needlessly

```
[2024-03-21T08:31:44.569585495-05:00] INFO [visor]: Changing skysocks-client Settings to map["--addr":":1080" "--http":":1081" "--srv":"03894b70efab29edcb5669cda5c34e47a6efce9130849faeaac4c3776e69d7b152" "app":"skysocks-client"]
[2024-03-21T08:31:44.569626939-05:00] INFO [visor:config]: Flushing config to file. config_version="unknown" filepath="/opt/skywire/skywire.json"
[2024-03-21T08:31:44.569965083-05:00] INFO [visor:config]: Flushing config to file. config_version="unknown" filepath="/opt/skywire/skywire.json"
[2024-03-21T08:31:44.570108433-05:00] INFO [visor:config]: Flushing config to file. config_version="unknown" filepath="/opt/skywire/skywire.json"
[2024-03-21T08:31:44.570244989-05:00] INFO [visor:config]: Flushing config to file. config_version="unknown" filepath="/opt/skywire/skywire.json"
[2024-03-21T08:31:44.570396409-05:00] INFO [visor:config]: Flushing config to file. config_version="unknown" filepath="/opt/skywire/skywire.json"

```

the config seems to be flushed excessively here

**Comment by mrpalide** [comment]
All comments from Moses fixed in last two commits.

**Comment by 0pcom** [comment]
please make the timeout 0 by default.

**Review by 0pcom — APPROVED** [review]

**Pull request merged**
