### PR TITLE
Remove the left menu bar from the manager

### PR DESCRIPTION
**Pull request by Senyoret1**
Did you run `make format && make check`?
The go code was not changed. `npm run lint` and `npm run build` were used.

 Changes:	
- The left menu bar was removed.
- As the left bar was originally created in a way which required a service for adding options to it and now it is no needed, the service was removed. While doing this several parts or the code were changed or moved, to avoid code duplications and make things more maintainable, as the service made the code more complex.
- The previous tab bar component now is in charge of showing the options menu, in large and small screens.
- Various other small improvements.

How to test this PR:
Just use the manager normally. The left menu bar will not be shown and, instead, there will be a button for openning the menu in the top right corner.

NOTE: some parts of the code need to be cleaned. That will be done after deciding some details about the design.

### CODE REVIEW

**Review by jdknives — COMMENTED** [review]
Good job @Senyoret1 . I think the changes are fine given that we need to add a different landing page for the VPN client in any case. I think we can merge that as soon as the code is cleaned up.

**Comment by Senyoret1** [comment]
The last commit includes the following changes:
- The final style for the return button has been implemented and the code has been cleaned.
- Some small errors that were left with the initial changes are now solved.
- Improvements were made to the top bar shown in mobile devices.

@jdknives With these changes the PR should be ready

**Review by jdknives — APPROVED** [review]
@Senyoret1 please merge as soon as the conflict is resolved. Good job.

**Comment by Senyoret1** [comment]
The last commits include the following changes:
- The conflicts were solved.
- A small bug that prevented the menu to be showed correctly in the settings page was solved.

**Pull request merged**
