### PR TITLE
Fix delays in keepalive packet tests

### LINKED ISSUE #554: Test handlePacket_keepalive fails
**Describe the bug**
```
--- FAIL: TestRouter_handleTransportPacket (2.23s)
    --- FAIL: TestRouter_handleTransportPacket/handlePacket_keepalive (0.12s)
        router_test.go:366: 
            	Error Trace:	router_test.go:366
            	            				router_test.go:344
            	Error:      	Received unexpected error:
            	            	routing table: rule keep-alive timeout exceeded
            	Test:       	TestRouter_handleTransportPacket/handlePacket_keepalive
```

Test fails in this build https://travis-ci.com/github/skycoin/skywire/jobs/401873214#L2844

### PR DESCRIPTION
**Pull request by nkryuchkov**
Did you run `make format && make check`? Yes

Fixes #554

 Changes:	
-  Fix delays in keepalive packet tests

How to test this PR:
- Run `make check`

### CODE REVIEW

**Comment by jdknives** [comment]
Ran `make check` in a loop for about 10 repetitions. Seems to work fine.

**Review by jdknives — APPROVED** [review]

**Comment by taras-skycoin** [comment]
[failing_tests.txt](https://github.com/skycoin/skywire/files/5591618/failing_tests.txt)
Got some errors.

**Comment by nkryuchkov** [comment]
@taras-skycoin Thank you for reporting. This error looks like a separate issue to me, because it happened inside `Test_router_NoiseRouteGroups`, but the changes I made are located inside `TestRouter_handleTransportPacket`.

**Comment by jdknives** [comment]
Will merge and make a new ticket for the error your encountered. @taras-skycoin @nkryuchkov

**Pull request merged**
