### PR TITLE
AppStats: Connection Duration Addition to API

### LINKED ISSUE #895: It is not possible to know the duration of the VPN connection
Currently it is not possible to know how long has it been since the VPN client app has been connected. The VPN UI was designed for showing this value, as it could be useful for the user, but it was removed until the API provides a way to get this data.

### PR DESCRIPTION
**Pull request by alexadhy**
Did you run `make format && make check`? yes

Fixes #895 

 Changes:	
- Added Connection Duration to the vpn-client

TODO:
- [X] Adds the duration to the API when user requires visor overview / connections stats.
- [X] Also generates the mock and readmegen

How to test this PR:
- Run the `vpn-client` app from the visor via UI / cli
- Run the VPN UI
- Connect to any vpn-server
- Check the connection duration field in json

Screen Shot 2021-10-04 at 21 43 02

### CODE REVIEW

**Comment by alexadhy** [comment]
@Senyoret1 can you also try this?

**Review by mrpalide — APPROVED** [review]
Good. Functionality is OK and code is clear to me.

**Comment by Senyoret1** [comment]
I did not check the code, but the functionality appears to be working well. Is the time in seconds?

**Comment by alexadhy** [comment]
> I did not check the code, but the functionality appears to be working well. Is the time in seconds?

it is, is it ok ?

**Comment by Senyoret1** [comment]
Yes, seconds is ok for me

**Comment by ersonp** [comment]
Everything looks good. I just had one suggestion. We should send `connection_duration` here `http://localhost:8000/api/visors/<pk>/apps/vpn-client/connections` 
```json
[
   {
      "is_alive":true,
      "latency":57,
      "upload_speed":2283,
      "download_speed":411,
      "bandwidth_sent":215672,
      "bandwidth_received":235619,
      "error":""
   }
]
```

**Comment by alexadhy** [comment]
@ersonp done

**Review by ersonp — APPROVED** [review]
The code looks good and everything is working as intended.

**Review by jdknives — APPROVED** [review]

**Pull request merged**
