### PR TITLE
new/update flags on skywire-cli

### LINKED ISSUE #1046: prevent erroneous hypervisor configuration
When the config is generated like this:

```
skywire-cli config gen --hypervisor-pks <visor-pk> -ro skywire-config.json
```

If the visor pk in question is the public key contained already in skywire-config.json then the above command should produce the same result as the following

```
skywire-cli config gen -iro skywire-config.json
```

That is, trying to set a visor to use it's own public key as hypervisor should generate the same configuration as intentionally generating the config with hypervisor enabled.

Currently this is not the behavior

need to default to producing a working config as much as possible. This is likely what someone intended to do if they did the first command.

This also represents an edge-case for auto configuration, when it might happen coincidentally or by happenstance. So it is preferable for this to be addressed.

### PR DESCRIPTION
**Pull request by mrpalide**
Did you run `make format && make check`?

Fixes #1046 #1050 #1054 #1061

 Changes:	
- added `--public-rpc` flag to change CLIAddr from `localhost:3435` to `:3435`.
- added comparing step on adding hypervisors keys on `--hypervisor-pks <visor-pk>` flag, that if key equal to visor PK, then change this visor to hypervisor.
- added `--vpn-server-enable` flag to make vpn-server app autostart attribute *true*
- improve `--package` flag to distinguished between hypervisor and visor, and change its config output file name
- add a checking `--output` or `-o` flag, and if set was used then override `-p` and `-s` flag

How to test this PR:
- build at this PR by `make build`
- generate config with `./skywire-cli config gen --public-rpc`
- check for CLIAddr value, should be `:3435`
- add visor pk as hypervisor pks by `skywire-cli config gen --hypervisor-pks <visor-pk> -ro skywire-config.json`
- check config file that hypervisors should be empty `[]`, and hypervisor config part should added to config file.
- generate/update config with `./skywire-cli config gen -r --vpn-server-enable`
- check config file to confirm that vpn-server autostart is true
- generate config twice with `-pi` and `-p` to check their different name
- generate config with `-pir` or `-sr` with `-o config.json` flag to see override functionality

### CODE REVIEW

**Comment by 0pcom** [comment]
cli_addr should actually be ":3545"

I think it's equivalent to 0.0.0.0 for the ip address to be blank but the port is listed

**Review by jdknives — APPROVED** [review]

**Comment by 0pcom** [comment]
We need consistency in the default behavior for some things.

Is enable-auth to be considered default? If so, can you make sure it is evenly implemented, it was changed to not enabled by default in the -p flag but the default when you give no arguments is enabled

and can you put a flag for the config generation to `--disable-auth` also, if we go with the aforementioned default?

**Comment by mrpalide** [comment]
As had conversation with Moses on matrix, we want these changes:
- [x] disable OS detection in runtime, and set flag instead
  -  as default set to `linux`, and can set by `--os windows` or `--os macos` flag.
- [x] disable auth in hypervisor as default, and be enabled by `-p` flag, or set OS to `windows` or `macos`
- [x] set `enable-auth` and `disable-auth` flag separately
- [x] remove `-s` flag completely
- [x] all apps be available as default, and remove each by flags
  - you should separate apps by `,`, same as `--disable-apps skysocks,vpn-server`

**Review by jdknives — APPROVED** [review]
Looks alright. Only need to double check we are not using the deprecated flag in Skybian still.

**Review by jdknives — APPROVED** [review]

**Pull request merged**
