### PR TITLE
Switch systray repo

### LINKED ISSUE #1165: Systray is not CGO free
**Describe the bug**
Current systray repo is old and also never maintain anymore. We have a problem with CGO related of systray that make dependency problem for us. We should use other forks that are maintain and also has CGO free feature.

### PR DESCRIPTION
**Pull request by mrpalide**
Did you run `make format && make check`? Yes

Fixes #1165 #1167

 Changes:	
- use our fork of fyne-io fork, actually skycoin/systray
- improve vpn status of systray

How to test this PR:
1. #1165
    - `make build-systray`
    - run in other machine that doesn't have systray dependencies. 
2. #1167 
    - do changes on 1167 bug report and run again (both with correct and wrong dsmgd server address), no race condition should happened.

### CODE REVIEW

**Comment by 0pcom** [comment]
I get the following error with `make build-systray`

```
cmd/skywire-visor/skywire-visor.go:9:2: systray_linux.go: parsing //go:build line: unexpected token linux
make: *** [Makefile:219: bin-systray] Error 1
```

That should be easy enough to fix.

Please pull the latest commits from develop so I can test this with the skywire-autoconfig script included with the packages.

**Comment by mrpalide** [comment]
> I get the following error with `make build-systray`
> 
> ```
> cmd/skywire-visor/skywire-visor.go:9:2: systray_linux.go: parsing //go:build line: unexpected token linux
> make: *** [Makefile:219: bin-systray] Error 1
> ```
> 
> That should be easy enough to fix.
> 
> Please pull the latest commits from develop so I can test this with the skywire-autoconfig script included with the packages.

It's OK on fresh ubuntu 20.04 with its dependencies and Go v1.17.9
image

**Comment by ersonp** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa7451e]

goroutine 8 [running]:
github.com/skycoin/skywire/internal/gui.getAvailPublicVPNServers(0xc0002279d0, 0xbd2017, 0xc000509f48)
        /home/erson/Workspace/Go/skywire/internal/gui/gui.go:351 +0x4fe
github.com/skycoin/skywire/internal/gui.initVpnClientBtn(0xc000250000, 0x0, 0xc00000eba0)
        /home/erson/Workspace/Go/skywire/internal/gui/gui.go:224 +0x36b
github.com/skycoin/skywire/internal/gui.GetOnGUIReady.func2()
        /home/erson/Workspace/Go/skywire/internal/gui/gui.go:90 +0xad
github.com/mrpalide/systray.Register.func2()
        /home/erson/Workspace/Go/skywire/vendor/github.com/mrpalide/systray/systray.go:98 +0x32
created by github.com/mrpalide/systray.Register
        /home/erson/Workspace/Go/skywire/vendor/github.com/mrpalide/systray/systray.go:96 +0xc8
```

**Comment by mrpalide** [comment]
Seems run on prod config file 🤔

On Monday, May 2, 2022, Erson Pereira ***@***.***> wrote:
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa7451e]
>
> goroutine 8 [running]:
>
github.com/skycoin/skywire/internal/gui.getAvailPublicVPNServers(0xc0002279d0,
0xbd2017, 0xc000509f48)
> /home/erson/Workspace/Go/skywire/internal/gui/gui.go:351 +0x4fe
> github.com/skycoin/skywire/internal/gui.initVpnClientBtn(0xc000250000,
0x0, 0xc00000eba0)
> /home/erson/Workspace/Go/skywire/internal/gui/gui.go:224 +0x36b
> github.com/skycoin/skywire/internal/gui.GetOnGUIReady.func2()
> /home/erson/Workspace/Go/skywire/internal/gui/gui.go:90 +0xad
> github.com/mrpalide/systray.Register.func2()
> /home/erson/Workspace/Go/skywire/vendor/
github.com/mrpalide/systray/systray.go:98 +0x32
> created by github.com/mrpalide/systray.Register
> /home/erson/Workspace/Go/skywire/vendor/
github.com/mrpalide/systray/systray.go:96 +0xc8
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/proxy/bOeJSRuJVRveNox__EUu4zdkmMRjcJCpeq1i-w2pENBNjuc06mLv1yrA91qRcNK5mh-cLFWOCHLqUnJh1loAFPMovE1Na34xnKKVIh-lYdAUeQ36uBbOY7SW8kfKco4dbe3Gw5_9svgol-Xvd7AIEr8fhKOIr4DETzI4xzerF049Gjhmm9nnLrrpirhpCr2MmJXxw3g6GvFjwouPzLm2swut5ZH4Iw4jTwst1xLC8A=s0-d-e1-ft#https://github.com/notifications/beacon/AS334235AG2ATZDOWFLWS3LVH6YJRA5CNFSM5UU6FAF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOIJYVAEQ.gif>Message
ID: ***@***.***>

**Comment by mrpalide** [comment]
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa7451e]
> 
> goroutine 8 [running]:
> github.com/skycoin/skywire/internal/gui.getAvailPublicVPNServers(0xc0002279d0, 0xbd2017, 0xc000509f48)
>         /home/erson/Workspace/Go/skywire/internal/gui/gui.go:351 +0x4fe
> github.com/skycoin/skywire/internal/gui.initVpnClientBtn(0xc000250000, 0x0, 0xc00000eba0)
>         /home/erson/Workspace/Go/skywire/internal/gui/gui.go:224 +0x36b
> github.com/skycoin/skywire/internal/gui.GetOnGUIReady.func2()
>         /home/erson/Workspace/Go/skywire/internal/gui/gui.go:90 +0xad
> github.com/mrpalide/systray.Register.func2()
>         /home/erson/Workspace/Go/skywire/vendor/github.com/mrpalide/systray/systray.go:98 +0x32
> created by github.com/mrpalide/systray.Register
>         /home/erson/Workspace/Go/skywire/vendor/github.com/mrpalide/systray/systray.go:96 +0xc8
> ```

Seems run on prod config file...

**Comment by ersonp** [comment]
> Seems run on prod config file...

Yes my bad, works on test.

**Comment by mrpalide** [comment]
> > Seems run on prod config file...
> 
> Yes my bad, works on test.

It should not happened after clean redis, but I fixed it in #d3e0f33 rn.

**Review by ersonp — APPROVED** [review]

**Pull request merged**
