### PR TITLE
Additional features for configuring skysocks-client in the manager

### LINKED ISSUE #314: Implement proxy discovery client.
Supersedes #15

### PR DESCRIPTION
**Pull request by Senyoret1**
Did you run `make format && make check`?
The go code was not changed. `npm run lint` and `npm run build` were used.

Maybe Fixes #314

 Changes:	
- Now the configuration modal window for the skysocks-client  app shows the list of nodes obtained from the proxy discovery service. Options for filtering the list were added.
- The history has been improved.
- Various other small improvements.

Notes:
- This PR includes the changes made in #315
- The PR still lack pagination options.
- The PR is currently connecting to a local instance of the proxy discovery service.
- The list obtained from the proxy discovery service does not include information about the auth state, so it was not possible to include that information or to use it for filtering.

How to test this PR:
Use the `make integration-run-proxy` command of the `skywire-services` repo and check the configuration options of the skysocks-client app.

### CODE REVIEW

**Comment by Senyoret1** [comment]
The last commits update the branch and include pagination for the proxy discovery tab of the skysocks-client config modal window.

**Comment by Senyoret1** [comment]
The lastest commit includes the following changes:
- The code for connecting the manager to the proxy discovery service was updated to work with the lastest version of the service.
- Elements which are no longer available in the proxy discovery service were removed from the UI.
- Now, when filtering the results of the proxy discovery service, the UI highlights in the results the terms the user used as filters.
- Now, in production builds, the url used for connecting with the proxy discovery service is `http://proxy.discovery.skywire.cc`. In dev builds the connection is made to a local instance of the proxy discovery service via the dev server proxy, to avoid problems with the CORS policy.

**Comment by Senyoret1** [comment]
The lasteast commit includes the following changes:
- Now the connection to the proxy discovery service is made using https if the manager was openned using https.
- The port was removed from the UI of the proxy discovery service.

**Comment by Senyoret1** [comment]
The previous commits where cherry picked and force push was used to make the PR work well with the changes made to the develop branch.

**Comment by Senyoret1** [comment]
The last commits include the following changes:
- The conflicts were solved.
- Some changes were made to make the PR continue working.

**Comment by Senyoret1** [comment]
The last commits include the following changes:
- Now the discovery service is accessible from http and https.
- The separators of the list now have the correct color.

**Review by jdknives — APPROVED** [review]

**Pull request merged**
